export const toursData = [
  {
    id: 1,
    image: '/tours/manali.png',
    location: 'Manali',
    title: 'Magical Manali & Solang Valley Adventure',
    price: 12999,
    originalPrice: 18999,
    discount: '32%',
    rating: 4.8,
    reviews: 256,
    duration: '5 Days / 4 Nights',
    maxPeople: 15,
    tag: 'Adventure',
    description: 'Immerse yourself in the breathtaking beauty of Manali and the thrill of Solang Valley. This adventure includes snow sports, serene walks through pine forests, and visits to ancient temples.',
    highlights: ['Solang Valley Snow Sports', 'Hadimba Devi Temple Visit', 'Beas River Rafting', 'Old Manali Cafe Crawl'],
  },
  {
    id: 2,
    image: '/tours/goa.png',
    location: 'Goa',
    title: 'Romantic Goa Beach Getaway',
    price: 15999,
    originalPrice: 22999,
    discount: '30%',
    rating: 4.7,
    reviews: 189,
    duration: '4 Days / 3 Nights',
    maxPeople: 20,
    tag: 'Honeymoon',
    description: 'Enjoy the sun-kissed beaches and vibrant nightlife of Goa. This getaway offers a perfect mix of relaxation and romance with private beach dinners and scenic boat rides.',
    highlights: ['Private Sunset Dinner', 'South Goa Heritage Tour', 'Dolphin Sighting Trip', 'Beachside Yoga Session'],
  },
  {
    id: 3,
    image: '/tours/kerala.png',
    location: 'Kerala',
    title: 'Kerala Backwaters & Houseboat Experience',
    price: 18999,
    originalPrice: 25999,
    discount: '27%',
    rating: 4.9,
    reviews: 312,
    duration: '6 Days / 5 Nights',
    maxPeople: 12,
    tag: 'Family',
    description: 'Drift through the serene backwaters of Alleppey on a luxury houseboat. Experience authentic Kerala lifestyle, lush greenery, and mouth-watering local cuisine.',
    highlights: ['Luxury Houseboat Stay', 'Munnar Tea Garden Tour', 'Kathakali Performance', 'Ayurvedic Massage Session'],
  },
  {
    id: 4,
    image: '/tours/rajasthan.png',
    location: 'Rajasthan',
    title: 'Royal Rajasthan Heritage Tour',
    price: 22999,
    originalPrice: 30999,
    discount: '26%',
    rating: 4.6,
    reviews: 178,
    duration: '7 Days / 6 Nights',
    maxPeople: 18,
    tag: 'Cultural',
    description: 'Walk through the majestic palaces and forts of Rajasthan. Discover the rich history of the Rajputana era in Jaipur, Udaipur, and Jodhpur.',
    highlights: ['Amber Fort Elephant Ride', 'City Palace Guided Tour', 'Desert Camel Safari', 'Cultural Folk Dance Show'],
  },
  {
    id: 5,
    image: '/tours/ladakh.png',
    location: 'Ladakh',
    title: 'Leh Ladakh High Altitude Expedition',
    price: 35000,
    originalPrice: 45000,
    discount: '22%',
    rating: 4.9,
    reviews: 145,
    duration: '8 Days / 7 Nights',
    maxPeople: 12,
    tag: 'Adventure',
    description: 'The ultimate adventure in the land of high passes. Visit Pangong Lake, Nubra Valley, and experience the unique culture of the Himalayas.',
    highlights: ['Pangong Lake Camping', 'Khardung La Pass', 'Magnetic Hill', 'Shanti Stupa'],
  },
  {
    id: 6,
    image: '/tours/santorini.png',
    location: 'Santorini',
    title: 'Greek Islands Luxury Cruise',
    price: 85000,
    originalPrice: 110000,
    discount: '23%',
    rating: 4.9,
    reviews: 420,
    duration: '10 Days / 9 Nights',
    maxPeople: 15,
    tag: 'Luxury',
    description: 'Sail through the crystal clear waters of the Aegean Sea. Experience the iconic blue-domed churches and world-famous sunsets of Santorini.',
    highlights: ['Oia Sunset Private Yacht', 'Wine Tasting Tour', 'Akrotiri Ruins', 'Black Sand Beaches'],
  },
  {
    id: 7,
    image: '/tours/venice.png',
    location: 'Venice',
    title: 'Romantic Venice Canal Tour',
    price: 62000,
    originalPrice: 75000,
    discount: '17%',
    rating: 4.8,
    reviews: 230,
    duration: '5 Days / 4 Nights',
    maxPeople: 10,
    tag: 'Romantic',
    description: 'Explore the floating city of Venice. Enjoy private gondola rides, visit historic squares, and indulge in authentic Italian cuisine.',
    highlights: ['Gondola Serenade', 'St. Mark\'s Basilica', 'Murano Glass Workshop', 'Doge\'s Palace Tour'],
  },
  {
    id: 8,
    image: '/tours/agra.png',
    location: 'Agra',
    title: 'Taj Mahal Heritage Experience',
    price: 4999,
    originalPrice: 7500,
    discount: '33%',
    rating: 4.9,
    reviews: 850,
    duration: '2 Days / 1 Night',
    maxPeople: 30,
    tag: 'Cultural',
    description: 'Witness the eternal symbol of love at sunrise. A perfectly guided tour of Agra Fort and the local artisanal markets.',
    highlights: ['Sunrise Taj Mahal View', 'Agra Fort Guided Tour', 'Mehtab Bagh Sunset', 'Local Inlay Art Demo'],
  },
  {
    id: 9,
    image: '/tours/bali.png',
    location: 'Bali',
    title: 'Bali Tropical Paradise Tour',
    price: 42000,
    originalPrice: 58000,
    discount: '28%',
    rating: 4.7,
    reviews: 340,
    duration: '7 Days / 6 Nights',
    maxPeople: 25,
    tag: 'Honeymoon',
    description: 'Experience the magic of Bali from the terraced rice fields of Ubud to the stunning beaches of Uluwatu.',
    highlights: ['Ubud Rice Terrace', 'Sacred Monkey Forest', 'Tanah Lot Temple', 'Jimbaran Seafood Dinner'],
  },
  {
    id: 10,
    image: '/tours/dubai.png',
    location: 'Dubai',
    title: 'Modern Dubai City & Desert Safari',
    price: 38000,
    originalPrice: 52000,
    discount: '27%',
    rating: 4.6,
    reviews: 560,
    duration: '5 Days / 4 Nights',
    maxPeople: 40,
    tag: 'Family',
    description: 'A perfect blend of modern luxury and traditional desert adventure. Experience Burj Khalifa and a thrilling dune bashing safari.',
    highlights: ['Burj Khalifa 124th Floor', 'Desert Dune Bashing', 'Dubai Mall Fountain Show', 'Old Souk Shopping'],
  },
  {
    id: 11,
    image: '/tours/paris.png',
    location: 'Paris',
    title: 'Eiffel Tower & Louvre Museum Tour',
    price: 55000,
    originalPrice: 70000,
    discount: '21%',
    rating: 4.9,
    reviews: 670,
    duration: '4 Days / 3 Nights',
    maxPeople: 20,
    tag: 'Cultural',
    description: 'Discover the City of Light. Visit the iconic Eiffel Tower, the world-famous Louvre Museum, and cruise along the Seine.',
    highlights: ['Louvre Priority Access', 'Eiffel Tower Dinner', 'Seine River Cruise', 'Montmartre Walk'],
  },
  {
    id: 12,
    image: '/tours/switzerland.png',
    location: 'Switzerland',
    title: 'Swiss Alps Panorama Rail Tour',
    price: 95000,
    originalPrice: 125000,
    discount: '24%',
    rating: 5.0,
    reviews: 180,
    duration: '9 Days / 8 Nights',
    maxPeople: 15,
    tag: 'Scenic',
    description: 'Traverse the majestic Swiss Alps on the world\'s most beautiful train routes. Experience Lucerne, Interlaken, and Zermatt.',
    highlights: ['Glacier Express Ride', 'Jungfraujoch Top of Europe', 'Lake Lucerne Boat Trip', 'Matterhorn Village Stay'],
  },
  {
    id: 13,
    image: '/tours/rishikesh.png',
    location: 'Rishikesh',
    title: 'Spiritual Ganga & Yoga Retreat',
    price: 8500,
    originalPrice: 12000,
    discount: '29%',
    rating: 4.8,
    reviews: 210,
    duration: '4 Days / 3 Nights',
    maxPeople: 50,
    tag: 'Spiritual',
    description: 'Find inner peace in the Yoga Capital of the World. Daily yoga sessions and a mesmerizing evening Ganga Aarti experience.',
    highlights: ['Daily Yoga & Meditation', 'Ganga Aarti at Parmarth', 'Neer Garh Waterfall Trek', 'Sattvic Organic Meals'],
  },
  {
    id: 14,
    image: '/tours/sikkim.png',
    location: 'Sikkim',
    title: 'North Sikkim Lacheng & Lachen Tour',
    price: 16500,
    originalPrice: 21000,
    discount: '21%',
    rating: 4.7,
    reviews: 155,
    duration: '6 Days / 5 Nights',
    maxPeople: 10,
    tag: 'Nature',
    description: 'Explore the hidden gems of North Sikkim. From the high-altitude Gurudongmar Lake to the valley of flowers in Yumthang.',
    highlights: ['Gurudongmar Lake', 'Yumthang Valley', 'Zero Point Expedition', 'Lachen Village Stay'],
  },
  {
    id: 15,
    image: '/tours/maldives.png',
    location: 'Maldives',
    title: 'Overwater Villa Luxury Retreat',
    price: 120000,
    originalPrice: 160000,
    discount: '25%',
    rating: 4.9,
    reviews: 290,
    duration: '5 Days / 4 Nights',
    maxPeople: 8,
    tag: 'Honeymoon',
    description: 'Pure luxury in the middle of the Indian Ocean. Stay in an overwater villa with direct access to crystal clear lagoons.',
    highlights: ['Private Overwater Villa', 'All-Inclusive Dining', 'Sunset Snorkeling Tour', 'Floating Breakfast'],
  },
  {
    id: 16,
    image: '/tours/kyoto.png',
    location: 'Kyoto',
    title: 'Kyoto Heritage & Zen Gardens',
    price: 75000,
    originalPrice: 95000,
    discount: '21%',
    rating: 4.8,
    reviews: 165,
    duration: '6 Days / 5 Nights',
    maxPeople: 15,
    tag: 'Cultural',
    description: 'Immerse yourself in ancient Japanese tradition. Visit thousand-year-old temples and experience an authentic tea ceremony.',
    highlights: ['Fushimi Inari Shrine', 'Arashiyama Bamboo Grove', 'Kinkaku-ji Golden Pavilion', 'Tea Ceremony Experience'],
  },
  {
    id: 17,
    image: '/tours/vietnam.png',
    location: 'Vietnam',
    title: 'Halong Bay Cruise & Hanoi Culture',
    price: 45000,
    originalPrice: 60000,
    discount: '25%',
    rating: 4.7,
    reviews: 310,
    duration: '7 Days / 6 Nights',
    maxPeople: 20,
    tag: 'Adventure',
    description: 'Cruise through the limestone karsts of Halong Bay and explore the bustling streets of Hanoi\'s Old Quarter.',
    highlights: ['Overnight Halong Cruise', 'Hanoi Street Food Tour', 'Cuchi Tunnels Visit', 'Mekong Delta Boat Trip'],
  },
  {
    id: 18,
    image: '/tours/udaipur.png',
    location: 'Udaipur',
    title: 'Lake City Royal Palace Tour',
    price: 14500,
    originalPrice: 19000,
    discount: '24%',
    rating: 4.8,
    reviews: 245,
    duration: '4 Days / 3 Nights',
    maxPeople: 15,
    tag: 'Royal',
    description: 'Experience the "Venice of the East". Stay in heritage hotels and cruise along the tranquil waters of Lake Pichola.',
    highlights: ['City Palace Museum', 'Jagmandir Island Cruise', 'Saheliyon Ki Bari', 'Vintage Car Museum'],
  },
  {
    id: 19,
    image: '/tours/hampi.png',
    location: 'Hampi',
    title: 'Hampi Ruins & Boulders Exploration',
    price: 9500,
    originalPrice: 13000,
    discount: '27%',
    rating: 4.9,
    reviews: 195,
    duration: '3 Days / 2 Nights',
    maxPeople: 25,
    tag: 'Heritage',
    description: 'Step back in time to the Vijayanagara Empire. Explore the boulder-strewn landscape and magnificent stone architecture.',
    highlights: ['Virupaksha Temple', 'Vittala Stone Chariot', 'Coracle Boat Ride', 'Matanga Hill Sunrise'],
  },
];
